### ISSUE TITLE
SampleStageFile must use the stage ID when creating the artefact directory

### ISSUE THREAD

**Issue by sinistral** [csm-adapt/sagittariidae#14]
The SampleStageFile model creates the a file name for the artefact using only the method ID.  This is not a sufficiently unique identifier (it's not inconceivable for the same method to be applied to a sample multiple times).  The stage ID must be included as a path component.

**Comment by bkappes** [comment]
Absolutely correct; in fact, applying the same method multiple times to the same sample will be more of a normal use case than an edge case. Thanks for catching that.
