### ISSUE TITLE
Robust file availability/existence verification

### ISSUE THREAD

**Issue by bkappes** [csm-adapt/sagittariidae#18]
This is present in app/models.py, but probably elsewhere as well. When checking whether a file exists, e.g. `open(trial).close()` will also fail if `trial` exists, but is not readable by the current user. Perhaps something like this to replace the try block:

```
while True:
    suffix = ...
    trial = ...
    if os.access(trial, os.F_OK):
        # file exists
        counter += 1
    else:
        # file doesn't exist
        return (suffix, counter)
```

or even some utility functions:

```
def file_exists(filename):
    return os.access(filename, os.F_OK)

def file_exists_and_is_readable(filename):
    return os.access(filename, os.F_OK & os.R_OK)

def file_exists_and_is_writable(filename):
    return os.access(filename, os.F_OK & os.W_OK)

def file_exists_and_is_read_write(filename):
    return os.access(filename, os.F_OK & os.R_OK & os.W_OK)
```

though such trivial functions may pollute our namespace to greater extent than the value they bring. Thoughts?

**Comment by sinistral** [comment]
I think the utility functions are a great idea; they are much more readable and convey intent better.  We can easily manage the namespace pollution by creating a `file` module to encapsulate these functions.
